### PR TITLE
feat: view on ipfs

### PR DESCRIPTION
**Pull request by olizilla**
Add a link to view a file or directory on https://ipfs.io/ipfs

screenshot 2018-08-02 16 15 37

### CODE REVIEW

**Comment by olizilla** [comment]
@dignifiedquire this goes a little way to your dream of file previews, while keeping the UI focused on the IPLD structrue

**Comment by VictorBjelkholm** [comment]
The link's text is a bit weird, aren't we already viewing it on IPFS? Maybe something like "View on ipfs.io" (stupid too as ipfs-companion would redirect for example) or "View on IPFS Gateway" makes more sense

**Comment by VictorBjelkholm** [comment]
Also, seems there is a bug where the router of explore.ipld.io picks up the url change instead of the browser itself opening it up

**Comment by dignifiedquire** [comment]
@olizilla appreciated!

**Comment by olizilla** [comment]
> there is a bug where the router of explore.ipld.io picks up the url change

Oh that's interesting, that'd happen if when the current domain matches the domain the site is loaded from. I'll fix it.

> The link's text is a bit weird, aren't we already viewing it on IPFS? Maybe something like "View on ipfs.io" (stupid too as ipfs-companion would redirect for example) or "View on IPFS Gateway" makes more sense.

Fair point. I'll have a think. I've been coming at this from the view that people would looing at explore.ipld.io but it should make sense on both.

**Pull request merged**
