### PR TITLE
Update dependencies to build on node 12+

### PR DESCRIPTION
**Pull request by jessicaschilling**
All of @andrew's helpful work over at https://github.com/ipfs-shipyard/ipld-explorer/pull/56, plus the following thanks to the [react18next migration guide](https://react.i18next.com/latest/migrating-v9-to-v10):
- Replace two instances of `translate` component with `withTranslation`
- Added `useSuspense.false` to init

### CODE REVIEW

**Comment by jessicaschilling** [comment]
I think this should be good for review - Travis is presumably failing because it's testing against Node 8.11. 

[Preview](https://bafybeifpyl3dkhivpswktavp3ij5ocrdqu3pr2k2ewgbe6hqvay4gexsmq.ipfs.dweb.link/#/explore/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D) looks good.

**Comment by andrew** [comment]
I also can't switch languages on the live site or the preview in Firefox, I wonder if it ever worked as it looks like all the i18n work is very similar to the code in js.ipfs.io

**Comment by jessicaschilling** [comment]
@andrew Thanks for the confirmation. I'd be inclined to merge this PR in since it looks like i18n is a separate issue. Thoughts?

**Comment by andrew** [comment]
The test failures look like a remote service at https://bundlesize-store.now.sh was down.

If you want to update the versions of node and npm on travis, the config is here: https://github.com/ipfs-shipyard/ipld-explorer/blob/master/.travis.yml#L3

Otherwise :shipit:

**Comment by lidel** [comment]
I bumped both travis and circleci to Node 12.17.0 and now both fail. 

Will look at this closer: ipfs-webui is using ipld-explorer-components v1.5.1 and works fine, so I'll try to align the deps to that.

**Pull request merged**
