### PR TITLE
chore: update ipld and deps

### PR DESCRIPTION
**Pull request by fsdiogo**
This makes ipld-explorer work with the new api changes from IPLD.

Also switched from `source-map-explorer` to `webpack-bundle-analyzer`.

Ref: https://github.com/ipfs-shipyard/ipfs-webui/pull/948

### CODE REVIEW

**Comment by fsdiogo** [comment]
I can't figure out Travis is always failing. If I checkout master it fails there too.

**Comment by olizilla** [comment]
You can debug the e2e tests  by running `DEBUG=true npm run test:e2e`

I'm seeing a js-ipfs  init error when running via puppeteer, which is weird, I don't see this when running  locally.

```console
Failed to initialise js-ipfs Error: No resolver found for codec "undefined"
    at IPLDResolver.put (index.js:221)
    at DAGNode.create (object.js:135)
    at multihashing (create.js:53)
    at Multihashing.Multihashing.digest (index.js:33)
    at index.js:15
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

screenshot 2019-02-06 at 12 03 56

**Comment by olizilla** [comment]
The test passes on `master`, worth noting that you either have to be running app before starting `npm run test:e2e` or you can run them both with `npm run test:e2e:ci`

**Comment by olizilla** [comment]
Oooh, i am able to recreate this locally if I delete all the indexedDB instances for the localhost:3000

**Comment by olizilla** [comment]
So the good news is that the smoke test caught an issue, we need to update js-ipfs on this PR!
The bad news is that the latest js-ipfs contains fancy spread operators that create-react-app won't transpile in deps, so I need to go and raise PRs to  fix that.

**Pull request merged**
